package tp2dpbo;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muhammad Rayhan Nur
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
      private dbConnection db;
    
    public Homepage(String namaUser) {
        db = new dbConnection();
        initComponents();
        setPanelDD();
       userLabel.setText("Halo, " + namaUser +"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        ddPanel = new javax.swing.JPanel();
        ddLabel = new javax.swing.JLabel();
        komikaPanel = new javax.swing.JPanel();
        komikaLabel = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        dataddPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanelDD = new javax.swing.JPanel();
        addDDButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dataKomikaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainPanelKomika = new javax.swing.JPanel();
        addKomikaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuPanel.setBackground(new java.awt.Color(12, 14, 23));

        userLabel.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(36, 186, 239));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Halo, Rayhan!");

        ddPanel.setBackground(new java.awt.Color(36, 186, 239));
        ddPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddPanelMouseClicked(evt);
            }
        });

        ddLabel.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 12)); // NOI18N
        ddLabel.setForeground(new java.awt.Color(255, 255, 255));
        ddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ddLabel.setText("Digital Download");

        javax.swing.GroupLayout ddPanelLayout = new javax.swing.GroupLayout(ddPanel);
        ddPanel.setLayout(ddPanelLayout);
        ddPanelLayout.setHorizontalGroup(
            ddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ddPanelLayout.setVerticalGroup(
            ddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        komikaPanel.setBackground(new java.awt.Color(36, 186, 239));
        komikaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        komikaLabel.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 12)); // NOI18N
        komikaLabel.setForeground(new java.awt.Color(255, 255, 255));
        komikaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        komikaLabel.setText("Komika");
        komikaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                komikaLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout komikaPanelLayout = new javax.swing.GroupLayout(komikaPanel);
        komikaPanel.setLayout(komikaPanelLayout);
        komikaPanelLayout.setHorizontalGroup(
            komikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(komikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(komikaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        komikaPanelLayout.setVerticalGroup(
            komikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, komikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(komikaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        aboutPanel.setBackground(new java.awt.Color(36, 186, 239));
        aboutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutPanelMouseClicked(evt);
            }
        });

        aboutLabel.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 12)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLabel.setText("About");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        logoutPanel.setBackground(new java.awt.Color(255, 51, 51));
        logoutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 12)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setText("Log Out");

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(komikaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(userLabel)
                .addGap(57, 57, 57)
                .addComponent(ddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(komikaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));

        dataddPanel.setBackground(new java.awt.Color(102, 102, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(422, 422));

        mainPanelDD.setBackground(new java.awt.Color(255, 255, 255));
        mainPanelDD.setPreferredSize(new java.awt.Dimension(720, 660));

        javax.swing.GroupLayout mainPanelDDLayout = new javax.swing.GroupLayout(mainPanelDD);
        mainPanelDD.setLayout(mainPanelDDLayout);
        mainPanelDDLayout.setHorizontalGroup(
            mainPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        mainPanelDDLayout.setVerticalGroup(
            mainPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanelDD);

        addDDButton.setText("Tambah Digital Download");
        addDDButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDDButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 24)); // NOI18N
        jLabel1.setText("DATA DIGITAL DOWNLOAD");

        javax.swing.GroupLayout dataddPanelLayout = new javax.swing.GroupLayout(dataddPanel);
        dataddPanel.setLayout(dataddPanelLayout);
        dataddPanelLayout.setHorizontalGroup(
            dataddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataddPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(dataddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dataddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addDDButton)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        dataddPanelLayout.setVerticalGroup(
            dataddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataddPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dataddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDDButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        dataKomikaPanel.setBackground(new java.awt.Color(255, 255, 51));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        mainPanelKomika.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelKomikaLayout = new javax.swing.GroupLayout(mainPanelKomika);
        mainPanelKomika.setLayout(mainPanelKomikaLayout);
        mainPanelKomikaLayout.setHorizontalGroup(
            mainPanelKomikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        mainPanelKomikaLayout.setVerticalGroup(
            mainPanelKomikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(mainPanelKomika);

        addKomikaButton.setText("Tambah Komika");
        addKomikaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addKomikaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addKomikaButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 1, 24)); // NOI18N
        jLabel2.setText("DATA KOMIKA");

        javax.swing.GroupLayout dataKomikaPanelLayout = new javax.swing.GroupLayout(dataKomikaPanel);
        dataKomikaPanel.setLayout(dataKomikaPanelLayout);
        dataKomikaPanelLayout.setHorizontalGroup(
            dataKomikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKomikaPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(dataKomikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKomikaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addKomikaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        dataKomikaPanelLayout.setVerticalGroup(
            dataKomikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKomikaPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(dataKomikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addKomikaButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dataKomikaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dataKomikaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setPanelDD() {
        mainPanelDD.removeAll();
        mainPanelDD.setLayout(new GridLayout(0, 3));
        
        try {
            String sql = "SELECT digital_download.id_digital_download, digital_download.judul, komika.nama_komika, digital_download.menit_durasi, digital_download.cover FROM digital_download INNER JOIN komika ON digital_download.id_komika = komika.id_komika";
            ResultSet res = db.selectQuery(sql);

            while (res.next()){
                int id = res.getInt("id_digital_download");
                String judul = res.getString("judul");
                String komika = res.getString("nama_komika");
                int durasi = res.getInt("menit_durasi");
                String path = res.getString("cover");
                 mainPanelDD.add(new CardDD(id, judul, komika, durasi, path));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        mainPanelDD.revalidate();
        mainPanelDD.repaint();
    }
    
    public void setPanelKomika() {
        mainPanelKomika.removeAll();
        mainPanelKomika.setLayout(new GridLayout(0, 2));
        
        try {
            String sql = "SELECT * FROM komika ORDER BY id_komika DESC";
            ResultSet res = db.selectQuery(sql);

            while (res.next()) {
                String namaKomika = res.getString("nama_komika");
                String path = res.getString("foto_komika");
                int idKomika = res.getInt("id_komika");
                mainPanelKomika.add(new CardKomika(idKomika, namaKomika, path));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        mainPanelKomika.revalidate();
        mainPanelKomika.repaint();
    }
    
    
    
    private void ddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddPanelMouseClicked
        // TODO add your handling code here:
        setPanelDD();
        dataddPanel.setVisible(true);
        dataKomikaPanel.setVisible(false);
    }//GEN-LAST:event_ddPanelMouseClicked

    private void komikaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_komikaLabelMouseClicked
        // TODO add your handling code here:
        setPanelKomika();
        dataKomikaPanel.setVisible(true);
        dataddPanel.setVisible(false);
    }//GEN-LAST:event_komikaLabelMouseClicked

    private void aboutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutPanelMouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "TP 2 DPBO - 2100192 - Muhammad Rayhan Nur - Ilmu Komputer C1");

    }//GEN-LAST:event_aboutPanelMouseClicked

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Logout",
			JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if  (opsi == JOptionPane.YES_OPTION) {
           new Login().setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void addKomikaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addKomikaButtonMouseClicked
        // TODO add your handling code here:
                FormKomika form = new FormKomika();
                form.setVisible(true);

                form.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                 setPanelKomika();
                }
                });
    }//GEN-LAST:event_addKomikaButtonMouseClicked

    private void addDDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDDButtonActionPerformed
        // TODO add your handling code here:
                FormDigitalDownload form = new FormDigitalDownload();
                form.setVisible(true);

                form.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                 setPanelDD();
                }
                });
    }//GEN-LAST:event_addDDButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton addDDButton;
    private javax.swing.JButton addKomikaButton;
    private javax.swing.JPanel dataKomikaPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel dataddPanel;
    private javax.swing.JLabel ddLabel;
    private javax.swing.JPanel ddPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel komikaLabel;
    private javax.swing.JPanel komikaPanel;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel mainPanelDD;
    private javax.swing.JPanel mainPanelKomika;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
